mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('todolist/', include('todolist.urls', namespace="todolist")),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from . import views

urlpatterns=[
        path('polls', views.index, name='index'),
        path('<int:question_id>/', views.detail, name='detail'),
        path('<int:question_id>/results/', views.results, name='results'),
        path('<int:question_id>/vote/', views.vote, name='vote'),
]

todolist/urls.py
from django.urls import path
from . import views

app_name = 'todolist'
urlpatterns=[
    path('', views.index, name='index'),
    path('additem/', views.additem , name='additem'),
    path('login/', views.login, name='login'),
    path('adduser/', views.addUser, name='addUser'),
    path('signout/', views.signout, name='signout'),
    path('thanks/', views.thanks, name='thanks'),
    path('ajax/update_item_status', views.update_item_status, name='update_item_status'),
    path('editItem/<int:id>', views.edit_item, name="edit_item"),
    path('deleteItem/<int:id>', views.deleteItem, name="deleteItem"),
    path('pomodorotimer/<int:id>', views.pomodoroTimer, name="pomodoroTimer"),
    path('pomodorotimer/ajax/updatepomodoro', views.updatePomodoroCount, name="updatePomodoroCount"),
    
]

todolist/models.py
from django.db import models
from django.utils import timezone
import datetime
from django.contrib.auth.models import User

class CustomUser(models.Model):
    username = models.CharField(max_length=70)
    password = models.CharField(max_length=50)
    email = models.EmailField()
    profile_name = models.CharField(max_length=70)
    def __str__(self):
        return self.username


# Create your models here
# .
class Item(models.Model):
    # create  a list item todo
    # user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    user  = models.ForeignKey(User, on_delete= models.CASCADE)
    todo_item = models.CharField(max_length=700)
    create_date = models.DateTimeField('Date created')
    start_date = models.DateTimeField('Date started',null=True)
    due_date = models.DateTimeField('Due date')
    status = models.BooleanField('Completed')
    pomodoro_estimate = models.IntegerField('Pomodoro Estimate')
    pomodoro_completed = models.IntegerField('Pomodoro Completed')
    recurring_task = models.BooleanField('Recurring')
    autoCompletePomodoro = models.BooleanField('Auto Pomodoro Complete')
    itemPriority = models.IntegerField('priority')
    tags = models.CharField(max_length=100)

    def __str__(self):
        return self.todo_item

# Create your models here.
class DeleteItem(models.Model):
    # create  a list item todo
    # user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    user  = models.ForeignKey(User, on_delete= models.CASCADE)
    todo_item = models.CharField(max_length=700)
    create_date = models.DateTimeField('Date created')
    start_date = models.DateTimeField('Date started',null=True)
    due_date = models.DateTimeField('Due date')
    status = models.BooleanField('Completed')
    pomodoro_estimate = models.IntegerField('Pomodoro Estimate')
    pomodoro_completed = models.IntegerField('Pomodoro Completed')
    recurring_task = models.BooleanField('Recurring')
    autoCompletePomodoro = models.BooleanField(' Auto Pomodoro Complete')
    itemPriority = models.IntegerField('priority')
    tags = models.CharField(max_length=100)

    def __str__(self):
        return self.todo_item



class dateStatusCheck(models.Model):
    today_date = models.DateField('Today Date')
    def __str__(self):
        return self.today_date.strftime('%Y-%m-%d')


class RecurringItemStatus(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
    #item_id = models.ForeignKey(Item, on_delete=models.CASCADE, related_name='todo_item_recur')
    item_id = models.IntegerField('Item')
    pomodoro_completed = models.IntegerField('Pomodoro Completed')
    pomodoro_estimated = models.IntegerField('Pomodoro Estimate')
    event_time  = models.DateTimeField('Event Timestamp')
    def __str__(self):
        return self.todo_item


class telegrambotUserMapping(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    telebotId = models.TextField('telegramId')
    event_time = models.DateTimeField('Event Timestamp')

todolist/forms.py
from django import forms
import datetime
from .models import Item
from .models import CustomUser
from django.contrib.admin.widgets import AdminDateWidget
from django.contrib.admin import widgets

class ItemForm(forms.Form):
    todo_item =  forms.CharField(widget=forms.Textarea(attrs={"rows":5, "cols":20})) 
    start_date = forms.DateTimeField(initial=datetime.date.today)  
    recurring_task = forms.BooleanField(required=False,widget=forms.RadioSelect())
    autoCompletePomodoro = forms.BooleanField(required=False,widget=forms.RadioSelect())
    due_date = forms.DateTimeField(initial=datetime.date.today)
    pomodoro_estimate = forms.IntegerField()
    pomodoro_completed = forms.IntegerField()
    itemPriority = forms.IntegerField()
    class Meta:
        model = Item
        fields = "__all__"


class ItemUpdateForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = "__all__"
   

class CustomUserForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = "__all__"

todolist/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Item, DeleteItem, CustomUser,RecurringItemStatus, dateStatusCheck
from django import forms
from .forms import ItemForm, ItemUpdateForm, CustomUserForm
from django.shortcuts import redirect
from django.http import QueryDict, JsonResponse
from django.forms.models import model_to_dict
from django.contrib.auth.forms import UserCreationForm , AuthenticationForm
from django.contrib.auth import authenticate , login as loginUser , logout
import json
from django.contrib.auth.decorators import login_required
import datetime
#from django.db.models import Item
# Create your views here.

@login_required(login_url='login/')
def index(request):
    if request.user.is_authenticated:
        user = request.user
        print(user.username)
        recurring_items = Item.objects.filter(recurring_task='1',user=user).order_by('status') 
        completed_items = Item.objects.filter(status='1',user=user).order_by('pomodoro_estimate')   
        list_of_items = Item.objects.filter(recurring_task='0',user=user,status='0').order_by('-create_date')
        context = {'recurring_items': recurring_items, 'list_of_items': list_of_items, 'completed_items': completed_items, 'logged_user':user.username,}
        checkAndUpdateRecurringTask()
        return render(request, 'todolist/index.html', context)
    else:
        return redirect("/todolist/")


def detail(request, item_id):
    task_item = get_object_or_404(Item, pk=item_id)
    return render(request, 'todolist/details.html', {'task_item': task_item})

def thanks(request):
    context = {}
    return  render(request, 'todolist/thanks.html', context)


@login_required(login_url='login/')
def additem(request):

    if request.user.is_authenticated:
        user = request.user
        print(user)


        # if this is a POST request we need to process the form data
        if request.method == 'POST':
            # create a form instance and populate it with data from the request:
            form = ItemForm(request.POST)
            # check whether it's valid:
            if form.is_valid():
                # process the data in form.cleaned_data as required
                # 
                # redirect to a new URL:
                #return HttpResponseRedirect('todolist/thanks/')
                #print(form.cleaned_data['todo_item'])
                user = user
                todo_item = form.cleaned_data['todo_item']
                start_date = form.cleaned_data['start_date']   
                create_date = datetime.date.today()        
                due_date = form.cleaned_data['due_date']            
                status = False
                pomodoro_estimate = form.cleaned_data['pomodoro_estimate']
                pomodoro_completed = form.cleaned_data['pomodoro_completed']
                recurring_task = form.cleaned_data['recurring_task']
                autoCompletePomodoro = form.cleaned_data['autoCompletePomodoro']
                if recurring_task == None:
                    recurring_task = False
                itemPriority = form.cleaned_data['itemPriority']
                item = Item(todo_item=todo_item, 
                            create_date=create_date, 
                            start_date=start_date,
                            due_date=due_date, 
                            status=status,
                            recurring_task=recurring_task,
                            pomodoro_estimate=pomodoro_estimate,
                            pomodoro_completed=pomodoro_completed,
                            autoCompletePomodoro=autoCompletePomodoro,
                            user=user,
                            itemPriority=itemPriority)
                item.save()
                return redirect('todolist:index')

        # if a GET (or any other method) we'll create a blank form
        else:
            form = ItemForm()

        return render(request, 'todolist/additem.html', {'form': form})

@login_required(login_url='login/')
def edit_item(request,id):
    if request.user.is_authenticated:
        user = request.user
        if request.method == "POST":
            recurringStatus = status = False # 040 6810 2816 2845 2840          
            if request.POST.get('recurring_task') == 'on':
                recurringStatus = True
            if request.POST.get('status') == 'on':
                status = True
            if request.POST.get('autoCompletePomodoro') == 'on':
                autoCompletePomodoroValue = True
            else:
                autoCompletePomodoroValue = False
            Item.objects.filter(pk=id).update(
                user = request.POST.get('user'),
                todo_item=request.POST.get('todo_item'), 
                start_date=request.POST.get('start_date'), 
                due_date=request.POST.get('due_date'), 
                status=status,
                recurring_task=recurringStatus,
                pomodoro_estimate=request.POST.get('pomodoro_estimate'),
                pomodoro_completed=request.POST.get('pomodoro_completed'),
                itemPriority=request.POST.get('itemPriority'),
                autoCompletePomodoro=autoCompletePomodoroValue,  
                )
            return redirect('todolist:index')
            
            
        if id:
            edit_item = Item.objects.get(id=id)
            form = ItemUpdateForm(instance=edit_item)
            print("showing the form")
            return render(request,'todolist/editItem.html',{'form':form})
        
@login_required(login_url='login/')
def update_item_status(request):
    if request.user.is_authenticated:
        user = request.user
        if request.method == 'POST':
            item_id = int(QueryDict(request.body)['id'])
            updateItem = Item.objects.get(id=item_id)
            # Check the condition for pomodoro complete 
            
            update_status = False
            present_status = updateItem.status
            if present_status == False:
                updated_status = True
            else:
                updated_status = False
            Item.objects.filter(pk=item_id).update(status=updated_status)
            
        return redirect("You updated the db status ")

@login_required(login_url='login/')
def reload_with_filter(request,id):
    if request.user.is_authenticated:
        user = request.user
        if request.method == 'GET':
            #filter_value = (QueryDict(request.body)['filter_value'])
            filter_value = id
            print(filter_value)
            print("entered reload with filter")
            if filter_value:
                recurring_items = Item.objects.filter(recurring_task='1',user=user,itemPriority=filter_value).order_by('status') 
                completed_items = Item.objects.filter(status='1',user=user,itemPriority=filter_value).order_by('pomodoro_estimate')   
                list_of_items = Item.objects.filter(recurring_task='0',user=user,status='0', itemPriority=filter_value).order_by('-create_date')
                context = {'recurring_items': recurring_items, 'list_of_items': list_of_items, 'completed_items': completed_items, 'logged_user':user.username,}
                checkAndUpdateRecurringTask()
                return render(request, 'todolist/index.html', context)
                
            else:
                return redirect("/todolist/")



@login_required(login_url='login/')
def deleteItem(request,id):

    item_id = id
    if item_id :
            # saving the deleted item in deleted table 
        user = request.user
        deleted_item = Item.objects.get(id=item_id)
        deleteObj = DeleteItem(
                               user=request.user,
                               todo_item=deleted_item.todo_item, 
                               create_date=deleted_item.create_date, 
                               due_date=deleted_item.due_date, 
                               status=deleted_item.status, 
                               recurring_task=deleted_item.recurring_task,
                               pomodoro_estimate=deleted_item.pomodoro_estimate,
                               pomodoro_completed=deleted_item.pomodoro_completed,
                               itemPriority=deleted_item.itemPriority,
                               autoCompletePomodoro=deleted_item.pomodoro_completed
                               )
        #deleteObj = DeletedItem(deleted_item)
        deleteObj.save()
        # delete it from items table 
        Item.objects.filter(pk=item_id).delete()
        return redirect('/todolist/')

@login_required(login_url='login/')
def pomodoroTimer(request,id):
    print(id)
    item_id = id
    if item_id :
            # saving the deleted item in deleted table 
        pomodoro_item = Item.objects.get(id=item_id)

    return render(request,"todolist/pomodorotimer.html",{'item':pomodoro_item})

@login_required(login_url='login/')
def updatePomodoroCount(request):
    if request.method == 'POST':
        print("reached pomodoro count")
        item_id = QueryDict(request.body)['id']
        print("update item id",item_id)
        user = request.user
        pomodoro_item = Item.objects.get(id=item_id)
        print(pomodoro_item.pomodoro_completed)
        
        if pomodoro_item:
            count = pomodoro_item.pomodoro_completed  + 1
            print(count)
            Item.objects.filter(pk=item_id).update(pomodoro_completed=count)

            if pomodoro_item.autoCompletePomodoro and pomodoro_item.pomodoro_estimate == count:
                Item.objects.filter(pk=item_id).update(status=True)

            print("The pomodoro status " + str(pomodoro_item.autoCompletePomodoro))
            
            itemDict = {'id':item_id, 'pomdoro_completed':count}

            recurItem = RecurringItemStatus(
                user=user,
                item_id=item_id,

todolist/templates/todolist/addUser.html
{% load static %}

<link rel='stylesheet' type="text/css" href="{% static 'todolist/style.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
<meta name="viewport" content="width=device-width, initial-scale=1">
<h2> Add New User </h2>

<form action = "" method = "post">
    {% csrf_token %}
    {{form.as_p }}
    <button type="submit" value=Save class="block"> Save </button>
    
    
</form>

<a href= "{% url 'todolist:index' %}" ><button type="submit"  class="home">Home</button> </a>

todolist/templates/todolist/additem.html
{% load static %}


<title>Todolist - Bharath</title>

<!-- Bootstrap 4 -->


<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
<link rel='stylesheet' type="text/css" href="{% static 'todolist/style.css' %}">

<h2> Add New Item </h2>



<!--

<div class="input-group date" id="datetimepicker1" data-target-input="nearest">
 Creation Date:   {{ form.create_date }}
    <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
      <div class="input-group-text"><i class="fa fa-calendar"></i></div>
    </div>
  </div>
  
  <script>
    $(function () {
      $("#datetimepicker1").datetimepicker({
        format: 'DD/MM/YYYY HH:mm',
      });
    });
  </script>
-->
<!--
<form action = "" method = "post">
    {% csrf_token %}
    {{form.as_p }}
    <input type="submit" value="Add Item">
</form>
-->
<form action="" method="post">
    {% csrf_token %}
    <div class="mb-3">
        <label for="id_todo_item">Item:</label>
        <textarea id="todo_item" type="text" name="todo_item" class="form-control" rows=3 required> </textarea>
    </div>
    <div class="mb-3">
        <label for="id_recurring_task">Recurring task:</label>
        <input type="checkbox" name="recurring_task" id="id_recurring_task">
    </div>

    <div class="mb-3">
        <label for="id_autoCompletePomodoro">Auto Complete Pomodoro:</label>
        <input type="checkbox" name="autoCompletePomodoro" id="id_autoCompletePomodoro">
    </div>

    <div>
        <label for="id_start_date">Start date:</label>
        </br>
        <input type="datetime-local" name="start_date" value="" required="" id="id_start_date">
    </div>
    <div>
        <label for="id_due_date">Due date:</label>
        </br>
        <input type="datetime-local" name="due_date" value="" required="" id="id_due_date">
    </div>

    <div>
        <label for="id_pomodoro_estimate">Pomodoro estimate:</label>
        </br>
        <input type="number" name="pomodoro_estimate" required="" value="3" id="id_pomodoro_estimate">
    </div>


    <div>
        <label for="id_pomodoro_completed">Pomodoro completed:</label>
        </br>
        <input type="number" name="pomodoro_completed" required="" value="0" id="id_pomodoro_completed">
    </div>

    <div>
        <label for="id_itemPriority">Choose the Priority of Item</label>
        <select id="id_itemPriority" name="itemPriority" size="1">
            <option value="1">1. Not Urgent Not Important</option>
            <option value="2">2. Not Urgent Important</option>
            <option value="3">3. Urgent Not Important</option>
            <option value="4">4. Urgent Important</option>
        </select>
    </div>


    </br>

    </br>
    <button type="submit" name="save" class="block" value="save"> Save</button>
    </br>
    </br>
    <a href="{% url 'todolist:index' %}"><button type="submit" class="home">Home</button> </a>
</form>

todolist/templates/todolist/editItem.html
{% load static %}


<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel='stylesheet' type="text/css" href="{% static 'todolist/style.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

<h2> Editing Item </h2>

<form action = "" method = "post">
    {% csrf_token %}
    {{form.as_p }}
    <input type="submit" value=Submit>
</form>

todolist/templates/todolist/login.html
{% load static %}

<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel='stylesheet' type="text/css" href="{% static 'todolist/style.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

<h2> Bharath Todo List Application  Login Page </h2>

<form action = "" method = "post">
    {% csrf_token %}
    {{form.as_p }}
    <input type="submit" value="Sign In" class="block" >
    
</form>

<a href="{% url 'todolist:addUser' %}">   <button type="button"    class="home"> Signup</button> </a>

todolist/templates/todolist/pomodorotimer.html
{% load static %}


{% block javascript %}
<script src="http://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script>

 
var gHours = 0;
var gMinutes = 0;
var gSeconds = 0;

var remainingTime;
var  pomodoroCountTrack = 0;
var  pausingTime = 0;
var  pauseFlag= 0;
var countdownHandle;

var audio = new Audio("{% static 'todolist/sounds/alarm_clock_2015.mp3' %}");

$(document).ready(function() {
  onPomodoroTimer();
});

function onPomodoroTimer(){

  stopTimer();

  gHours = 0;
  gMinutes = 25;
  gSeconds = 0;

  resetTimer();

  
  $('#shortButton').removeClass('btn-success');
  $('#longButton').removeClass('btn-success');
  $('#pomodoroButton').addClass('btn-success');
  
}

function onShortTimer(){

  stopTimer();

  gHours = 0;
  gMinutes = 5;
  gSeconds = 0;

  resetTimer();

  $('#pomodoroButton').removeClass('btn-success');
  $('#longButton').removeClass('btn-success');
  $('#shortButton').addClass('btn-success');
}

function onLongTimer(){

  stopTimer();

  gHours = 0;
  gMinutes = 15;
  gSeconds = 0;

  resetTimer();

  $('#pomodoroButton').removeClass('btn-success');
  $('#shortButton').removeClass('btn-success');
  $('#longButton').addClass('btn-success');
}

function onStartTimer(id){
  console.log('Start time id');
  console.log(id);
  item_id = id;
  stopTimer();
  startTimer(id);
};

function onStopTimer(){
  stopTimer();

};

function onResetTimer(){
  stopTimer();
  resetTimer();
}

function startAlarm(){
  if(remainingTime<1000)
  {
    audio.play();
  }
}


function onPauseTimer(){
  pauseTimer();
  
}

function startTimer(id) {

  var initialTime = new Date().getTime();


  countdownHandle=setInterval(function() {
    
    decrementTimer(id,initialTime);
  },2000);
  
 
 
}


function stopTimer() {
  clearInterval(countdownHandle);
  startAlarm();
}

function resetTimer(){
  


  remainingTime = (gHours*60*60*1000)+
  (gMinutes*60*1000)+
  (gSeconds*1000);
  renderTimer();
}

function pauseTimer(){
  pausingTime =  remainingTime;
  clearInterval(countdownHandle);
  console.log("Pausing time "+pausingTime);

}




function checkTimer(){
    

}

function renderTimer(){


  var deltaTime=remainingTime;

  //var deltaTime=count;
  var hoursValue=Math.floor(deltaTime/(1000*60*60));
  deltaTime=deltaTime%(1000*60*60);

  var minutesValue=Math.floor(deltaTime/(1000*60));
  deltaTime=deltaTime%(1000*60);

  var secondsValue=Math.floor(deltaTime/(1000));
  animateTime(hoursValue, minutesValue, secondsValue);
};


function animateTime(remainingHours, remainingMinutes, remainingSeconds) {

  // position
  $('#hoursValue').css('top', '0em');
  $('#minutesValue').css('top', '0em');
  $('#secondsValue').css('top', '0em');

  $('#hoursNext').css('top', '0em');
  $('#minutesNext').css('top', '0em');
  $('#secondsNext').css('top', '0em');

  var oldHoursString = $('#hoursNext').text();
  var oldMinutesString = $('#minutesNext').text();
  var oldSecondsString = $('#secondsNext').text();

  var hoursString = formatTime(remainingHours);
  var minutesString = formatTime(remainingMinutes);
  var secondsString = formatTime(remainingSeconds);

  $('#hoursValue').text(oldHoursString);
  $('#minutesValue').text(oldMinutesString);
  $('#secondsValue').text(oldSecondsString);

  $('#hoursNext').text(hoursString);
  $('#minutesNext').text(minutesString);
  $('#secondsNext').text(secondsString);

  // set and animate
  if(oldHoursString !== hoursString) {
    $('#hoursValue').animate({top: '-=1em'});
    $('#hoursNext').animate({top: '-=1em'});
  }

  if(oldMinutesString !== minutesString) {
    $('#minutesValue').animate({top: '-=1em'});
    $('#minutesNext').animate({top: '-=1em'});
  }

  if(oldSecondsString !== secondsString) {
    $('#secondsValue').animate({top: '-=1em'});
    $('#secondsNext').animate({top: '-=1em'});
  }
}


function formatTime(intergerValue){

  return intergerValue > 9 ? intergerValue.toString():'0'+intergerValue.toString();

}

function decrementTimer(id,initialTime){


  console.log('Initial time ',initialTime);
  var latestEpoch = new Date().getTime();
  // Get Caliculated time 
  var x = document.getElementById("pomodoroButton").className; 
  var y = document.getElementById("longButton").className

  if(pausingTime != 0)
    {
        pauseFlag = 1;
    } 


    if (x == 'btn btn-default btn-success' ){
      remainingTime =( (initialTime+1500000) -  latestEpoch) - (1500000- pausingTime)*pauseFlag;
     
    }
    else if (y == 'btn btn-default btn-success') 
    {
        remainingTime = ((initialTime+900000) -  latestEpoch) - (900000- pausingTime)*pauseFlag;
    }
    else{
        remainingTime = ((initialTime+300000) -  latestEpoch )- (300000- pausingTime)*pauseFlag;
    }
  

  console.log('remainingTime',remainingTime);
  //remainingTime-=(1*1000);

  if(remainingTime<1000){
    onStopTimer();
    var x = document.getElementById("pomodoroButton").className; 
    if (x == 'btn btn-default btn-success' ){
          console.log(pomodoroCountTrack);
          pomodoroCountUpdate(id);
          console.log("The element is pomodoro");
          if (pomodoroCountTrack < 4){
            onShortTimer();
            pomodoroCountTrack++;
          }
          else{
            onLongTimer();
            pomodoroCountTrack = 0;
          }
          
      }

      else{
          console.log("The element is not pomodoro");
      }


  }

  renderTimer();
 
}
  

function pomodoroCountUpdate(id) {
        
        console.log(id)
        $.ajax({
        type: 'POST',
        headers: {'X-CSRFToken': '{{ csrf_token }}'},
        url: "ajax/updatepomodoro",
        data: {
          'id': id
        },
        dataType: 'json',
        success: function (data) {
          //alert("Pomodoro Completed ");
          console.log("The pomodoro is completed");
        }
      });


    }

</script>   

{% endblock %}

<meta name="viewport" content="width=device-width, initial-scale=0.85">
<link rel='stylesheet' type="text/css" href="{% static 'todolist/style.css' %}">
<link rel='stylesheet' type="text/css" href="{% static 'todolist/pomodoro-timer.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">







<div class="jquery-script-clear"></div>
</div>
</div>
  <div class="container" style="margin-top:150px;">
    <div class="page-header">
      <h1>{{item.todo_item}}</h1>
      <h4 class="text-center">Pomodoro Timer</h4>
      <h2 class="text-center">

        <span>
          <button id="pomodoroButton" class="btn btn-default" type="submit" onclick="onPomodoroTimer()" >Pomodoro</button>
          <button id="shortButton" class="btn btn-default" type="submit" onclick="onShortTimer()">Short Break</button>
          <button id="longButton" class="btn btn-default" type="submit" onclick="onLongTimer()">Long Break</button>
        </span>
      </h2>
    </div>

    <div class="panel panel-default">
      <div class="panel-body text-center">
        <div class="timer-time timer-container">
          <div class="timer-time-set timer-box" id="currentTime">
            <span id="hoursValue">00</span><span>:</span><span id="minutesValue">00</span><span>:</span><span id="secondsValue">00</span>
          </div>
          <div class="timer-time-set timer-box" id="nextTime">
            <span id="hoursNext">00</span><span>:</span><span id="minutesNext">00</span><span>:</span><span id="secondsNext">00</span>
          </div>
        </div>
        <div>
          <button id="restartButton" class="btn btn-warning btn-lg" type="submit" onclick="onResetTimer()">
            <span class="glyphicon glyphicon-step-backward" aria-hidden="true"></span> Reset
          </button>

          <button id="startButton" class="btn btn-primary btn-lg" type="submit" onclick="onStartTimer('{{item.id}}')">
            <span class="glyphicon glyphicon-play" aria-hidden="true"></span> Start
          </button>
          <button id="pauseButton" class="btn btn-success btn-lg" type="submit" onclick="onPauseTimer()">
            <span class="glyphicon glyphicon-stop" aria-hidden="true"></span> Pause
          </button>
          
        </div>
    </br>
        <button id="stopButton" class="btn btn-danger btn-lg" type="submit" onclick="onStopTimer()">
            <span class="glyphicon glyphicon-stop" aria-hidden="true"></span> Stop
          </button>
      </div>

    </div>

  </div>

  <br>

  <div class="text-center">
    <a href= "{% url 'todolist:index' %}" ><button type="button"  class="btn btn-warning">Home</button> </a>
</div>